
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import "https://deno.land/x/xhr@0.1.0/mod.ts";

const GROQ_API_KEY = Deno.env.get("GROQ_API_KEY");

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Get Supabase client info from request
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      throw new Error('Missing Authorization header');
    }

    // Get the request data
    const { messages, userId } = await req.json();
    
    if (!messages || !Array.isArray(messages) || messages.length < 2) {
      throw new Error('Invalid messages data - need at least a user and assistant message');
    }

    console.log(`Processing summarization for ${messages.length} messages`);
    
    // Format conversation for the AI
    // Prepare system prompt for summarization with more direct tone
    const systemPrompt = `Extract key factual information, technical concepts, and industry knowledge from the conversation. 
      Remove any personal information, identifiers, company names, specific projects, or identifying details. 
      Format the output as concise, factual bullet points about magnetic technology, industry knowledge, 
      or technical concepts that will be useful for future reference. Be direct and matter-of-fact.`;

    if (!GROQ_API_KEY) {
      console.error("GROQ_API_KEY is not set");
      throw new Error("GROQ_API_KEY is not configured");
    }

    // Call GROQ API to summarize
    const groqResponse = await fetch("https://api.groq.com/openai/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${GROQ_API_KEY}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: "llama3-70b-8192",
        messages: [
          { role: "system", content: systemPrompt },
          ...messages.map(msg => ({
            role: msg.role,
            content: msg.content
          }))
        ],
        temperature: 0.1, // Updated: Changed from 0.5 to 0.1 for more factual summaries
        max_tokens: 1024
      })
    });

    if (!groqResponse.ok) {
      const errorText = await groqResponse.text();
      console.error(`GROQ API error: ${errorText}`);
      throw new Error(`Failed to generate summary: ${errorText}`);
    }

    const data = await groqResponse.json();
    const summary = data.choices[0].message.content;

    if (!summary || !summary.trim()) {
      console.error("No summary was generated");
      throw new Error("No summary was generated by the AI");
    }

    console.log("Summary generated successfully");

    // Store the summary in training_data table
    const supabaseUrl = Deno.env.get("SUPABASE_URL");
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");

    if (!supabaseUrl || !supabaseKey) {
      throw new Error("Missing Supabase configuration");
    }

    // Create a title from the first 50 characters of the first message
    const title = `Summary: ${new Date().toISOString().split('T')[0]} - ${
      messages[0].content.slice(0, 50).replace(/[^\w\s]/gi, '')
    }`;

    // Ensure document_type is valid
    const documentType = "company"; // Keep this consistent to avoid validation errors

    const insertBody = {
      content: {
        title: title,
        summary: summary,
        source: "direct-summarization",
        original_content: messages.map(m => `${m.role}: ${m.content}`).join("\n\n")
      },
      document_type: documentType,
      scope: "global",
      // Use the passed userId or a default system ID
      user_id: userId || "00000000-0000-0000-0000-000000000000"
      // Note: embedding will be automatically generated by the database trigger
    };

    console.log("Attempting to insert with body:", JSON.stringify(insertBody));

    const insertResponse = await fetch(`${supabaseUrl}/rest/v1/training_data`, {
      method: "POST",
      headers: {
        "apikey": supabaseKey,
        "Authorization": `Bearer ${supabaseKey}`,
        "Content-Type": "application/json",
        "Prefer": "return=minimal"
      },
      body: JSON.stringify(insertBody)
    });

    if (!insertResponse.ok) {
      const errorText = await insertResponse.text();
      console.error(`Error storing summary:`, errorText);
      throw new Error(`Failed to store summary: ${errorText}`);
    }

    console.log("Summary stored successfully with embedding auto-generated by database trigger");

    return new Response(JSON.stringify({ 
      success: true,
      message: "Conversation summarized and added to knowledge base with embedding",
      summary: summary
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });

  } catch (error) {
    console.error('Error in save-ai-summary function:', error);
    return new Response(JSON.stringify({ 
      success: false,
      error: error.message 
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }
});
